/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTeamsRouteImport } from './routes/_authenticated/teams'
import { Route as AuthenticatedSummaryRouteImport } from './routes/_authenticated/summary'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedMasterRouteImport } from './routes/_authenticated/master'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContributionsRouteImport } from './routes/_authenticated/contributions'
import { Route as AuthenticatedChecklistRouteImport } from './routes/_authenticated/checklist'
import { Route as AuthenticatedBudgetRouteImport } from './routes/_authenticated/budget'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeamsRoute = AuthenticatedTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSummaryRoute = AuthenticatedSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMasterRoute = AuthenticatedMasterRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContributionsRoute =
  AuthenticatedContributionsRouteImport.update({
    id: '/contributions',
    path: '/contributions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChecklistRoute = AuthenticatedChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBudgetRoute = AuthenticatedBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/budget': typeof AuthenticatedBudgetRoute
  '/checklist': typeof AuthenticatedChecklistRoute
  '/contributions': typeof AuthenticatedContributionsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/master': typeof AuthenticatedMasterRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/summary': typeof AuthenticatedSummaryRoute
  '/teams': typeof AuthenticatedTeamsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/budget': typeof AuthenticatedBudgetRoute
  '/checklist': typeof AuthenticatedChecklistRoute
  '/contributions': typeof AuthenticatedContributionsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/master': typeof AuthenticatedMasterRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/summary': typeof AuthenticatedSummaryRoute
  '/teams': typeof AuthenticatedTeamsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/budget': typeof AuthenticatedBudgetRoute
  '/_authenticated/checklist': typeof AuthenticatedChecklistRoute
  '/_authenticated/contributions': typeof AuthenticatedContributionsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/master': typeof AuthenticatedMasterRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRoute
  '/_authenticated/summary': typeof AuthenticatedSummaryRoute
  '/_authenticated/teams': typeof AuthenticatedTeamsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/budget'
    | '/checklist'
    | '/contributions'
    | '/dashboard'
    | '/master'
    | '/staff'
    | '/summary'
    | '/teams'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/budget'
    | '/checklist'
    | '/contributions'
    | '/dashboard'
    | '/master'
    | '/staff'
    | '/summary'
    | '/teams'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/budget'
    | '/_authenticated/checklist'
    | '/_authenticated/contributions'
    | '/_authenticated/dashboard'
    | '/_authenticated/master'
    | '/_authenticated/staff'
    | '/_authenticated/summary'
    | '/_authenticated/teams'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/teams': {
      id: '/_authenticated/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AuthenticatedTeamsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/summary': {
      id: '/_authenticated/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof AuthenticatedSummaryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/master': {
      id: '/_authenticated/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof AuthenticatedMasterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contributions': {
      id: '/_authenticated/contributions'
      path: '/contributions'
      fullPath: '/contributions'
      preLoaderRoute: typeof AuthenticatedContributionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checklist': {
      id: '/_authenticated/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof AuthenticatedChecklistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/budget': {
      id: '/_authenticated/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof AuthenticatedBudgetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBudgetRoute: typeof AuthenticatedBudgetRoute
  AuthenticatedChecklistRoute: typeof AuthenticatedChecklistRoute
  AuthenticatedContributionsRoute: typeof AuthenticatedContributionsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMasterRoute: typeof AuthenticatedMasterRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRoute
  AuthenticatedSummaryRoute: typeof AuthenticatedSummaryRoute
  AuthenticatedTeamsRoute: typeof AuthenticatedTeamsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBudgetRoute: AuthenticatedBudgetRoute,
  AuthenticatedChecklistRoute: AuthenticatedChecklistRoute,
  AuthenticatedContributionsRoute: AuthenticatedContributionsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMasterRoute: AuthenticatedMasterRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRoute,
  AuthenticatedSummaryRoute: AuthenticatedSummaryRoute,
  AuthenticatedTeamsRoute: AuthenticatedTeamsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
